import { Inter, Vollkorn } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "@/components/footer";
import Home from "./page";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
const vollkorn = Vollkorn({ subsets: ["latin"]})

export const metadata = {
  title: "EvaTouch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="md:px-20 px-4">
          <Header />
          <section>
          {children}
          </section>
        </div>
        <Footer />
      </body>
    </html>
  );
}
